VIA_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no

RGB_MATRIX_ENABLE = yes # Requiered
RGB_MATRIX_CUSTOM_USER = yes

# ENABLE_MILKSHAKE = yes

RGB_MATRIX_CUSTOM_EFFECT_IMPLS = yes
# RGB_MATRIX_CUSTOM_my_cool_effect2 = yes

# ENABLE_RGB_MATRIX_SOLID_COLOR = yes
# ENABLE_RGB_MATRIX_CUSTOM_my_cool_effect2 = yes
